<?xml version="1.0"?>
<package format="3">
  <name>tb3_server</name>
  <version>0.1.0</version>
  <description>TB3 patrol server (ROS 2, ament_cmake)</description>

  <maintainer email="you@example.com">you</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>nav2_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
<buildtool_depend>ament_cmake_python</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
    <buildtool_depend>ament_cmake_python</buildtool_depend>
  </export>
</package>
