qr_waypoints:
  "1": {x: 0.0, y: 0.0, yaw: 0.0}
  "2": {x: 1.0, y: 0.0, yaw: 0.0}
  "3": {x: 1.0, y: 1.0, yaw: 1.57}
  "4": {x: 0.0, y: 1.0, yaw: 3.14}

homes:
  "/tb3_1": {x: -0.5, y: 0.0, yaw: 0.0}
  "/tb3_2": {x: -1.0, y: 0.0, yaw: 0.0}
